Repository opensearch-project/opensearch-ci, pull requests merged in 2022-07, with the labels that each got.

#152 Add jdk14 as it is required by OS 1.x gradle check
  resources/baseJenkins.yaml
  test/data/test_env.yaml
Labels: bug

#153 Migrate perf test agent setups to public jenkins
  lib/ci-stack.ts
  lib/compute/agent-nodes.ts
Labels: enhancement

#155 Add initial windows packer templates for ami
  packer/README.md
  packer/config/windows/launch-config.json
  packer/jenkins-agent-win2016-x64.json
  packer/jenkins-agent-win2019-x64-alpine-wsl.json
  packer/jenkins-agent-win2019-x64.json
  packer/scripts/windows/pip-install.ps1
  packer/scripts/windows/scoop-install-alpinewsl.ps1
  packer/scripts/windows/scoop-install-commons.ps1
  packer/scripts/windows/scoop-setup.ps1
  packer/scripts/windows/smb-setup-2019-plus.ps1
  packer/scripts/windows/smb-setup.ps1
  packer/scripts/windows/userdata.ps1
  packer/scripts/windows/wsl-setup.ps1
Labels: enhancement

#158 Add Mac agent support
  README.md
  lib/ci-stack.ts
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
  lib/compute/jenkins-main-node.ts
  lib/network/ci-external-load-balancer.ts
  test/ci-cdn-stack.test.ts
  test/compute/agent-node-config.test.ts
  test/data/jenkins.yaml
Labels: enhancement

#159 Make sure gradle check agent only runs once
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
Labels: enhancement

#160 Make agent label have consistent capital naming (opensearch-ci)
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
Labels: enhancement

#161 Add macos version to the label
  lib/compute/agent-node-config.ts
Labels: enhancement

#162 Add yum db cleanup to AL2 and remove lock to Ubuntu2004
  lib/compute/agent-nodes.ts
Labels: bug, enhancement

#167 Remove fixed password setups in Windows Packer
  packer/config/windows/launch-config.json
  packer/jenkins-agent-win2016-x64.json
  packer/jenkins-agent-win2019-x64-alpine-wsl.json
  packer/jenkins-agent-win2019-x64.json
Labels: enhancement

#170 Make jenkins jdk tool match manifest jdk naming
  resources/baseJenkins.yaml
  test/data/test_env.yaml
Labels: enhancement

#169 Adding new Windows agent and organize Mac agent configurations
  README.md
  lib/ci-stack.ts
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
  lib/compute/jenkins-main-node.ts
  lib/security/ci-security-groups.ts
  packer/README.md
  packer/jenkins-agent-win2016-x64.json
  packer/jenkins-agent-win2019-x64-alpine-wsl.json
  packer/jenkins-agent-win2019-x64.json
  packer/scripts/windows/userdata.ps1
Labels: enhancement

#172 Fix gradle check by removing old caches and add back docker-compose
  lib/compute/agent-nodes.ts
Labels: bug
