Repository opensearch-project/opensearch-ci, pull requests merged in 2022-10, with the labels that each got.

#186 Migrate cdk from version 1.x to latest version 2.37.1
  .eslintrc.js
  bin/ci-stack.ts
  cdk.json
  lib/auditing/ci-audit-logging.ts
  lib/buildArtifacts/artifacts-public-access.ts
  lib/buildArtifacts/build-artifacts-permissions.ts
  lib/ci-cdn-stack.ts
  lib/ci-config-stack.ts
  lib/ci-stack.ts
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
  lib/compute/jenkins-main-node.ts
  lib/compute/run-additional-commands.ts
  lib/constructs/cloudwatch-agent.ts
  lib/constructs/cloudwatch/metrics-section.ts
  lib/monitoring/ci-alarms.ts
  lib/network/ci-external-load-balancer.ts
  lib/security/ci-security-groups.ts
  package-lock.json
  package.json
  test/ci-cdn-stack.test.ts
  test/ci-stack.test.ts
  test/compute/agent-node-config.test.ts
Labels: enhancement

#205 Update amis to run from prod jenkins accounts
  lib/compute/agent-nodes.ts
  packer/jenkins-agent-macos12-x64.json
  packer/scripts/macos/macos-agentsetup.sh
Labels: enhancement

#208 Add new node version 14.20.0 to Windows Agent
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement, windows

#209 Replace nvm with volta for Windows Agent
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement

#210 Add Windows Gradle Check Jenkins Agent
  lib/ci-stack.ts
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement, windows

#211 Restore windows to use 1 executor max
  lib/compute/agent-nodes.ts
Labels: bug

#212 Add new env var MINGW_BIN for k-NN
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement, windows

#213 Add k-NN required zip and JDK19 for Core
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
  resources/baseJenkins.yaml
  test/data/test_env.yaml
Labels: enhancement, windows

#214 Resolve incorrectly added env vars for Windows
  lib/compute/agent-nodes.ts
  packer/scripts/windows/scoop-install-commons.ps1
Labels: bug
