Repository opensearch-project/opensearch-ci, pull requests merged in 2023-05, with the labels that each got.

#282 Resolve AL2 pip package path issues
  packer/scripts/al2/al2-agent-setups.sh
Labels: bug, packer

#283 Tweak al2 agents to use pipenv fix ami in #282
  lib/compute/agent-nodes.ts
Labels: bug, packer

#285 Export path in al2 for pip
  packer/scripts/al2/al2-agent-setups.sh
Labels: bug, packer

#286 Add #285 AL2 AMI in the agents
  lib/compute/agent-nodes.ts
Labels: enhancement, packer

#280 Support JDK-20 builds on Jenkins
  lib/compute/agent-node-config.ts
  packer/scripts/ubuntu2004/ubuntu2004-agent-setups.sh
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement

#289 Add JDK20 enabled Agent Nodes to Jenkins
  lib/compute/agent-nodes.ts
Labels: agents

#292 Update windows ami updated in PR #291
  lib/compute/agent-nodes.ts
Labels: enhancement, windows, packer

#293 Add chromium installation to the windows ami
  packer/scripts/windows/scoop-install-alpinewsl.ps1
  packer/scripts/windows/scoop-install-commons.ps1
Labels: enhancement, windows, packer

#294 Replace temurin20 with openjdk20 as former is not available on Windows
  packer/scripts/windows/scoop-install-commons.ps1
Labels: bug, windows, packer

#295 Correct chromium path found in Windows
  packer/scripts/windows/scoop-install-commons.ps1
Labels: bug, windows, packer

#296 Update windows ami id from #295
  lib/compute/agent-nodes.ts
Labels: enhancement

#300 Add more timeouts and idle time for Windows AMI
  lib/compute/agent-node-config.ts
  packer/scripts/windows/scoop-install-alpinewsl.ps1
  packer/scripts/windows/scoop-install-commons.ps1
Labels: bug, windows, packer

#299 Update AMI ID for Windows Agent in #298 #300
  lib/compute/agent-nodes.ts
Labels: windows, packer
