Repository opensearch-project/opensearch-ci, pull requests merged in 2025-02, with the labels that each got.

#524 Update windows https transport to use openssl
  packer/scripts/windows/scoop-install-commons-docker-support.ps1
Labels: windows, agents, release

#525 Switch scoop installation to 0.4.2 version
  packer/scripts/windows/scoop-setup.ps1
Labels: windows, agents, release

#526 Replace #525 Windows AMI and extend startup time
  lib/compute/agent-node-config.ts
  lib/compute/agent-nodes.ts
Labels: windows, agents, release

#522 Update ALB to use RECOMMENDED_TLS SslPolicy to remove TLS1.1
  lib/network/ci-external-load-balancer.ts
Labels: enhancement

#529 Fix configHelper bug for authTpye default
  lib/compute/jenkins-main-node.ts
Labels: bug
